name = "DistributionsHEP"
uuid = "0d0d6f60-fb7b-48ca-90bb-e14e8b1655a7"
authors = ["Pere Mato <pere.mato@cern.ch>"]
version = "0.3.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
Distributions = ">= 0.25"
Polynomials = ">= 4"
QuadGK = ">= 2"
Random = ">= 1"
SpecialFunctions = ">= 2"
Test = ">= 1"

[extras]
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "QuadGK"]
